[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/upload"
  to = "/upload.html"
  status = 200

[functions."rockbrief"]
  schedule = "0 12 * * *"

[functions."rockbrief-watchdog"]
  schedule = "30 12 * * *"
